import requests
import json
session_id =  'CHANGEME'
length = '10' #number of rows
filename = 'muteahhitler.json' #don't forget to put '.json' at the end
cookies = {
    'ASP.NET_SessionId': session_id,
}

headers = {
    'Accept': 'application/json, text/javascript, */*; q=0.01',
    'Accept-Language': 'tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    # 'Cookie': 'ASP.NET_SessionId=3vracds0bdd4uvtppvro1vml',
    'Origin': 'https://yambis.csb.gov.tr',
    'Referer': 'https://yambis.csb.gov.tr/Muteahhit/Index',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 OPR/107.0.0.0',
    'X-Requested-With': 'XMLHttpRequest',
    'sec-ch-ua': '"Not A(Brand";v="99", "Opera";v="107", "Chromium";v="121"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
}

data = {
    'draw': '1',
    'columns[0][data]': 'KisiId',
    'columns[0][name]': '',
    'columns[0][searchable]': 'true',
    'columns[0][orderable]': 'false',
    'columns[0][search][value]': '',
    'columns[0][search][regex]': 'false',
    'columns[1][data]': 'VergiNo',
    'columns[1][name]': 'VergiNo',
    'columns[1][searchable]': 'true',
    'columns[1][orderable]': 'true',
    'columns[1][search][value]': '',
    'columns[1][search][regex]': 'false',
    'columns[2][data]': 'TcNo',
    'columns[2][name]': 'TcNo',
    'columns[2][searchable]': 'true',
    'columns[2][orderable]': 'true',
    'columns[2][search][value]': '',
    'columns[2][search][regex]': 'false',
    'columns[3][data]': 'Ad',
    'columns[3][name]': 'Ad',
    'columns[3][searchable]': 'true',
    'columns[3][orderable]': 'true',
    'columns[3][search][value]': '',
    'columns[3][search][regex]': 'false',
    'columns[4][data]': 'Soyad',
    'columns[4][name]': 'Soyad',
    'columns[4][searchable]': 'true',
    'columns[4][orderable]': 'true',
    'columns[4][search][value]': '',
    'columns[4][search][regex]': 'false',
    'columns[5][data]': 'Tanim',
    'columns[5][name]': 'Tanim',
    'columns[5][searchable]': 'true',
    'columns[5][orderable]': 'true',
    'columns[5][search][value]': '',
    'columns[5][search][regex]': 'false',
    'columns[6][data]': 'KisiTuru',
    'columns[6][name]': 'KisiTuru',
    'columns[6][searchable]': 'true',
    'columns[6][orderable]': 'true',
    'columns[6][search][value]': '',
    'columns[6][search][regex]': 'false',
    'columns[7][data]': 'Il',
    'columns[7][name]': 'Il',
    'columns[7][searchable]': 'true',
    'columns[7][orderable]': 'true',
    'columns[7][search][value]': '',
    'columns[7][search][regex]': 'false',
    'columns[8][data]': 'GeciciMi',
    'columns[8][name]': 'GeciciMi2',
    'columns[8][searchable]': 'true',
    'columns[8][orderable]': 'true',
    'columns[8][search][value]': '',
    'columns[8][search][regex]': 'false',
    'columns[9][data]': 'ElektronikHaberlesmeMuteahhitiMi',
    'columns[9][name]': 'ElektronikHaberlesmeMuteahhitiMi',
    'columns[9][searchable]': 'true',
    'columns[9][orderable]': 'true',
    'columns[9][search][value]': '',
    'columns[9][search][regex]': 'false',
    'columns[10][data]': 'YetkiBelgeNo',
    'columns[10][name]': 'YetkiBelgeNo',
    'columns[10][searchable]': 'true',
    'columns[10][orderable]': 'true',
    'columns[10][search][value]': '',
    'columns[10][search][regex]': 'false',
    'columns[11][data]': 'Durum',
    'columns[11][name]': 'Durum',
    'columns[11][searchable]': 'true',
    'columns[11][orderable]': 'true',
    'columns[11][search][value]': '',
    'columns[11][search][regex]': 'false',
    'columns[12][data]': 'YasaklamaNedeni',
    'columns[12][name]': 'YasaklamaNedeni',
    'columns[12][searchable]': 'true',
    'columns[12][orderable]': 'true',
    'columns[12][search][value]': '',
    'columns[12][search][regex]': 'false',
    'columns[13][data]': 'YapimMuteahhitiMi',
    'columns[13][name]': 'YapimMüteahhitiMi',
    'columns[13][searchable]': 'true',
    'columns[13][orderable]': 'true',
    'columns[13][search][value]': '',
    'columns[13][search][regex]': 'false',
    'columns[14][data]': 'KararGrupTipi',
    'columns[14][name]': 'KararGrupTipi',
    'columns[14][searchable]': 'true',
    'columns[14][orderable]': 'true',
    'columns[14][search][value]': '',
    'columns[14][search][regex]': 'false',
    'columns[15][data]': 'YikimMuteahhitiMi',
    'columns[15][name]': 'YikimMuteahhitiMi',
    'columns[15][searchable]': 'true',
    'columns[15][orderable]': 'true',
    'columns[15][search][value]': '',
    'columns[15][search][regex]': 'false',
    'columns[16][data]': 'YikimKararGrupTipi',
    'columns[16][name]': 'YikimKararGrupTipi',
    'columns[16][searchable]': 'true',
    'columns[16][orderable]': 'true',
    'columns[16][search][value]': '',
    'columns[16][search][regex]': 'false',
    'start': '0',
    'length': length,
    'search[value]': '',
    'search[regex]': 'false',
}

response = requests.post(
    'https://yambis.csb.gov.tr/Muteahhit/getMuteahhitKisilerJSON',
    cookies=cookies,
    headers=headers,
    data=data,
)
r_json = response.json()
print(f"Status: {response.status_code}")
print(f"Number of rows: {len(r_json.get('data'))}")
with open(filename,"w") as f:
    json.dump(r_json,f,indent=4)
print(f"Saved to file: {filename}")
